version: "3.8"
services:
  db:

    image: postgres:latest
    environment:
      - POSTGRES_USER=vallghall
      - POSTGRES_PASSWORD=test-l0
      - POSTGRES_DB=test-db
    ports:
      - "5432:5432"

  nats:
    image: nats-streaming
    command:
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--cluster_id"
      - "nats-test"
      - "--port"
      - "4222"
      - "--http_port"
      - "8222"
    ports:
      - "4222:4222"
      - "8222:8222"

  server:
    build: .
    depends_on:
      - db
      - nats
    ports:
      - "8080:8080"
